### ISSUE TITLE
Remove steamName, profilePublic and skill from api request body

### ISSUE THREAD

**Issue by michaelsandner** [diveflo/fair-teams-ai#63]
We should remove skill, profilePublic and steamName from the request body because it is not needed. As a first step this attributes should be optional, so the application is still working after the api change.

```
[
  {
    "name": "string",
    "steamName": "string",   //remove
    "profilePublic": true,   //remove
    "steamID": "string",
    "skill": {}   //remove
  }
]
```

**Comment by diveflo** [comment]
Check Swagger for new API :)
